#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import os
import re
from collections import defaultdict
from pathlib import Path


SOURCE_ROOT_CANDIDATES = (
    "/data/work/st156392/mergedDataset/derivatives",
)
DEFAULT_OUTPUT_ROOT = Path(
    "/home/st156392/topoplots/more"
)
TASK = "freeView"
FILENAME_RE = re.compile(
    rf"^(sub-[^_]+)_task-{re.escape(TASK)}_run-(\d+)_proc-(clean|eyelink)_raw\.fif$"
)


def resolve_source_root(requested_root: Path | None) -> Path:
    if requested_root is not None:
        return requested_root

    for candidate in SOURCE_ROOT_CANDIDATES:
        candidate_path = Path(candidate)
        if candidate_path.is_dir():
            return candidate_path

    candidate_list = ", ".join(SOURCE_ROOT_CANDIDATES)
    raise SystemExit(
        "Could not find a usable derivatives3 source root. "
        f"Tried: {candidate_list}. Pass --source-root explicitly."
    )


def resolve_output_root(requested_root: Path | None, source_root: Path) -> Path:
    if requested_root is not None:
        return requested_root

    if source_root == Path(SOURCE_ROOT_CANDIDATES[0]):
        return source_root

    return DEFAULT_OUTPUT_ROOT


def parse_recordings(
    source_root: Path,
) -> dict[str, dict[str, list[tuple[int, Path]]]]:
    groups: dict[str, dict[str, list[tuple[int, Path]]]] = {
        "clean": defaultdict(list),
        "eyelink": defaultdict(list),
    }

    with os.scandir(source_root) as subject_entries:
        for subject_entry in subject_entries:
            if not subject_entry.is_dir() or not subject_entry.name.startswith("sub-"):
                continue

            eeg_dir = Path(subject_entry.path) / "eeg"
            if not eeg_dir.is_dir():
                continue

            with os.scandir(eeg_dir) as fif_entries:
                for fif_entry in fif_entries:
                    if not fif_entry.is_file():
                        continue

                    match = FILENAME_RE.match(fif_entry.name)
                    if match is None:
                        continue

                    subject_id, run_text, proc = match.groups()
                    groups[proc][subject_id].append((int(run_text), Path(fif_entry.path)))

    return groups


def to_output_path(source_path: Path, source_root: Path, output_root: Path) -> str:
    return str(output_root / source_path.relative_to(source_root))


def build_group_list(
    groups_by_subject: dict[str, list[tuple[int, Path]]],
    source_root: Path,
    output_root: Path,
) -> list[tuple[str, ...]]:
    group_list: list[tuple[str, ...]] = []

    for subject_id in sorted(groups_by_subject):
        sorted_runs = sorted(groups_by_subject[subject_id], key=lambda item: (item[0], item[1].name))
        group = tuple(
            to_output_path(source_path, source_root, output_root)
            for _, source_path in sorted_runs
        )
        if group:
            group_list.append(group)

    return group_list


def format_group(group: tuple[str, ...]) -> str:
    if len(group) == 1:
        return f"({json.dumps(group[0])},)"

    return "(" + ", ".join(json.dumps(path) for path in group) + ")"


def write_output(
    output_path: Path,
    clean_groups: list[tuple[str, ...]],
    raw_groups: list[tuple[str, ...]],
    *,
    source_root: Path,
    output_root: Path,
) -> None:
    lines = [
        "# Auto-generated by build_recording_groups2.py",
        f"# Verified via source root: {source_root}",
        f"# Emitted with output root: {output_root}",
        "",
        "CLEAN_GROUPS = [",
    ]

    for group in clean_groups:
        lines.append(f"    {format_group(group)},")

    lines.extend(
        [
            "]",
            "",
            "RAW_GROUPS = [",
        ]
    )

    for group in raw_groups:
        lines.append(f"    {format_group(group)},")

    lines.extend(["]", ""])
    output_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    script_dir = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(
        description=(
            "Build per-subject freeView recording groups from derivatives3, "
            "verifying files via one root and emitting absolute paths under another."
        )
    )
    parser.add_argument(
        "--source-root",
        type=Path,
        default=None,
        help=(
            "derivatives3 root used to discover and verify existing files. "
            "If omitted, the script prefers the local /pfs tree and falls back to bwuni-ws2."
        ),
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=None,
        help=(
            "Absolute root to use in the generated path strings. "
            "Defaults to the local /pfs tree, or to --source-root when that already is the /pfs tree."
        ),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=script_dir / "generated_recording_groups2.jl",
        help="Output file containing CLEAN_GROUPS and RAW_GROUPS.",
    )
    args = parser.parse_args()

    source_root = resolve_source_root(args.source_root)
    output_root = resolve_output_root(args.output_root, source_root)

    if not source_root.is_dir():
        raise SystemExit(f"Source root does not exist or is not a directory: {source_root}")

    recordings = parse_recordings(source_root)
    clean_groups = build_group_list(recordings["clean"], source_root, output_root)
    raw_groups = build_group_list(recordings["eyelink"], source_root, output_root)

    write_output(
        args.output,
        clean_groups,
        raw_groups,
        source_root=source_root,
        output_root=output_root,
    )

    print(f"CLEAN_GROUPS: {len(clean_groups)} groups")
    print(f"RAW_GROUPS: {len(raw_groups)} groups")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
